### ISSUE TITLE
Error: (SystemJS) ENOENT: no such file or directory, open '/path/to/my/module/npm:buffer@4.9.1'

### ISSUE THREAD

**Issue by mathieumg** [andyearnshaw/intern-systemjs-loader#3] opened 2016-09-13 21:40 UTC
``` bash
Error: Cannot find module 'node_modules/intern-systemjs-loader/main.js'
  at Function.Module._resolveFilename  <module.js:438:15>
  at Function.resolve  <internal/module.js:27:19>
  at <node_modules/intern/lib/executors/PreExecutor.js:498:32>
  at new Promise  <node_modules/intern/browser_modules/dojo/Promise.ts:411:3>
  at PreExecutor.swapLoader  <node_modules/intern/lib/executors/PreExecutor.js:489:11>
  at swapLoader  <node_modules/intern/lib/executors/PreExecutor.js:449:17>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
npm ERR! Test failed.  See above for more details.
```

Followed the demo configuration in the README. Not sure if it's related to https://github.com/andyearnshaw/intern-systemjs-loader/issues/1 or not.

I `cat`'d the file and everything is in order, so I'm wondering what is up. Thanks, looking forward to getting this work and finally upgrading my test suite to ES2015+ :)

**Edit:** This seems to only be happening when running through `npm run <script>`, if run the same command in the terminal it works correctly. It probably has to do with the working directory. Still investigating. I can get it to work if I change the path to `../intern-systemjs-loader/main.js`.

**Edit 2:** I'm not really familiar with SystemJS, but it seems it doesn't allow (not by default anyway) to omit filename extensions when requiring/importing them and most of my tests were designed like that, is there any way around it?

**Edit 3:** So I commented my old tests, made a new simple test and specified the extension, I get the following:

``` bash
Error: (SystemJS) ENOENT: no such file or directory, open '/path/to/my/module/npm:buffer@4.9.1'
    Error: ENOENT: no such file or directory, open '/path/to/my/module/npm:buffer@4.9.1'
        at Error (native)
    Error loading /path/to/my/module/npm:buffer@4.9.1 as "npm:buffer@4.9.1" from /path/to/my/module/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js
    Unable to load transpiler to transpile /path/to/my/module/tests/demo.js
    Error loading /path/to/my/module/tests/demo.js as "./demo.js" from /path/to/my/module/tests/all.js
No stack or location
```

**Comment by andyearnshaw** [comment] 2016-09-13 22:27
Heh, there's a few issues I need to work through, I know.  It's tough getting a consistent configuration between the Node & Browser configs, so I had to hack around it with this:

``` javascript
loaders: {
    'host-node': require.nodeRequire && require.nodeRequire.resolve('intern-systemjs-loader'),
    'host-browser': 'node_modules/intern-systemjs-loader/main.js'
},

// Configuration options for the module loader; any AMD configuration options supported by
// the specified AMD loader can be used here
loaderOptions: {
    transpiler: 'plugin-babel',
    babelOptions: { retainLines: true },

    map: {
        'plugin-text'           : '/node_modules/systemjs-plugin-text/text.js',
        'plugin-json'           : '/node_modules/systemjs-plugin-json/json.js',
        'plugin-babel'          : '/node_modules/systemjs-plugin-babel/plugin-babel.js',
        'systemjs-babel-build'  : '/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js',
        'sinon'                 : '/node_modules/sinon/pkg/sinon.js',
        'sinon-chai'            : '/node_modules/sinon-chai/lib/sinon-chai.js',
        'chai-as-promised'      : '/node_modules/chai-as-promised/lib/chai-as-promised.js'
    },

    meta: {
        '*.json': { loader: 'plugin-json' }
    }
}
```

The issue you're having now is outlined at https://github.com/systemjs/plugin-babel/issues/59.  Fixing the systemjs-plugin-babel version to 0.0.13 should work until there's a fix.

**Comment by mathieumg** [comment] 2016-09-14 00:19
> The issue you're having now is outlined at systemjs/plugin-babel#59. Fixing the systemjs-plugin-babel version to 0.0.13 should work until there's a fix.

That was it! Thanks, at least I get a test to run correctly now so I'll fiddle a bit more with it. Do you by any chance know how to get it to work so that extensions (like `.js`) are not required? Thank you for the quick reply, too!

**Edit:**  It's me, again! I'm trying to load node modules and I can't manage to do it. I tried:

``` js
import util from "util";
```

which gives me:

``` bash
Error: (SystemJS) ENOENT: no such file or directory, open '/path/to/my/module/util'
    Error: ENOENT: no such file or directory, open '/path/to/my/module/util'
        at Error (native)
```

I also tried:

``` js
import util from "intern/dojo/node!util";
```

which gives me:

``` bash
Error: (SystemJS) ENOENT: no such file or directory, open '/path/to/my/module/node_modules/intern/dojo/node.js'
    Error: ENOENT: no such file or directory, open '/path/to/my/module/node_modules/intern/dojo/node.js'
        at Error (native)
```

It could be relevant to show how to require a "normal" node module (either/both Node API or/and npm installed) in https://github.com/andyearnshaw/intern-systemjs-loader/blob/master/tests/sample.spec.js

**Comment by andyearnshaw** [comment] 2016-09-14 08:10
> Do you by any chance know how to get it to work so that extensions (like .js) are not required?

You should be able to add `defaultJSExtensions: true` to your `loaderOptions` in the Intern config.  I don't think this will be a standard thing for ES modules in the browser, though, so it might be best to get used to writing the extension.

> I'm trying to load node modules and I can't manage to do it.

When hacking around how Intern does this, I added a method to load node modules along with an alias:

``` javascript
import util from "@intern-systemjs-loader:node!util";
import util from "dojo/node!util";
```

I've just added (and published) the `intern/dojo/node` alias, so if you use one of the above or update to the latest version, it should work.

**Comment by mathieumg** [comment] 2016-09-14 12:44
I gave `defaultJSExtensions` a shot, but it tries to append `.js` even to Node modules, so then it can't find `util.js`. I also tried 

``` js
import util from "dojo/node!util";
```

after writing my post. It worked, however the problem happens again for the application code being tested. Same with file extensions. I imagine the loader would need to "let go" of resolving `require`/`import` statements once it recognizes it's dealing with a Node module. (and not a "normal" local file) That doesn't sound trivial statically, I don't know anything about the internals however. (For instance when you require or import `util`, Node first checks if it's in the `node_modules` chain of directories, then it checks if there's a file named `util.__` locally, then it checks if there's a folder named `util` locally and will load its `index.js` if it exists, etc.)

I've long been wanting to migrate my Intern tests to ES modules, but the Intern team seems adamant on sticking to the AMD format. I intended on using this module (which I just discovered yesterday) as a stepping stone to migrate the modules to ES and perhaps eventually look up another test suite, but in the long run perhaps I'd be better switching to something like https://github.com/avajs/ava however that requires a much bigger amount of rewriting and refactoring.

**Comment by andyearnshaw** [comment] 2016-09-15 08:15
I've been able to import Node modules in tests when using `intern-client` with no problems, the `dojo/node!` plugin simply uses Node's require to create a SystemJS module.  In the `intern-runner` environment, you can't do that because the tests run in the browser and Node's require isn't available.  If the node module is an npm-installed package, you need to reference the `index.js` directly.

The Intern team have expressed an interest in ES modules recently, but I think part of the problem is having an easy upgrade path for people with tests written in AMD.  SystemJS is the natural choice for Intern 4.0, I think.

I'll close this ticket since the original issues seem to be resolved.  Thanks for all the feedback!

**Closed as completed by andyearnshaw** 2016-09-15 08:15 UTC
